### ISSUE TITLE
Responses going to the wrong queue actions.

### ISSUE THREAD

**Issue by portaljumper007** [PirateGame/Pirate-Game-Backend#85]
BACK:gameHandler(debug): Response received: Use your shield to question: {'gameName': 'ARkayA', 'clientName': 'kUSVks', 'options': ['Do nothing', 'Use your shield'], 'labels': ['Rob', 'How do you want to respond?']}
[2021-01-19 17:43:21,012] ERROR in app: Exception on /api/submitResponse [POST]
Traceback (most recent call last):
  File "C:\Users\encha\Documents\GitHub\Pirate-Game-Backend\environment\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\encha\Documents\GitHub\Pirate-Game-Backend\environment\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\encha\Documents\GitHub\Pirate-Game-Backend\environment\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\encha\Documents\GitHub\Pirate-Game-Backend\environment\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\encha\Documents\GitHub\Pirate-Game-Backend\environment\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\encha\Documents\GitHub\Pirate-Game-Backend\environment\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\encha\Documents\GitHub\Pirate-Game-Backend\app.py", line 267, in submitResponse
    game.FRONTresponse(gameName, playerName, choice)
  File "c:\Users\encha\Documents\GitHub\Pirate-Game-Backend\game.py", line 825, in FRONTresponse
    def getRemainingQuestions(gameName):
  File "c:\Users\encha\Documents\GitHub\Pirate-Game-Backend\game.py", line 309, in turnHandle
    if self.turnProcess():
  File "c:\Users\encha\Documents\GitHub\Pirate-Game-Backend\game.py", line 269, in turnProcess
    out.append(self.about["clients"][clientName].actHandle())
  File "c:\Users\encha\Documents\GitHub\Pirate-Game-Backend\game.py", line 469, in actHandle
    #print("ACT HANDLE CALLED FOR", self.about["name"], "WITH QUEUES", self.about["actQueue"], self.about["beActedOnQueue"])#
  File "c:\Users\encha\Documents\GitHub\Pirate-Game-Backend\game.py", line 489, in act
    def act(self, whatHappened):
  File "c:\Users\encha\Documents\GitHub\Pirate-Game-Backend\game.py", line 437, in victimChoice
    elif self.about["type"] == "human":
KeyError: 'Use your shield'

**Comment by portaljumper007** [comment]
This should now be fixed.
